Makefile.am, configure.ac, src/asound/bluealsa-pcm.c, test/server-mock.c, test/test-alsa-pcm.c, test/test-ba.c, test/test-msbc.c
for playback, implement support for avail_min sw parameter, and generate internal events during the time synchronization sleep, so that applications can continue to write while the io thread sleeps.
this change enables using bluealsa with alsaloop, for example, and possibly other applications that attempt to synchronize 2 pcms with managed latency.
=> improve alsa pcm poll event generation

src/asound/bluealsa-ctl.c, src/asound/bluealsa-pcm.c, src/shared/dbus-client.c, src/shared/dbus-client.h, test/test-alsa-ctl.c, utils/aplay/aplay.c
Right now ALSA will be aware of our dB scaling range, so it will be possible to use functions like `snd_ctl_get_dB_range()`.
=> Provide ALSA control TLV data for dB calculation

utils/aplay/aplay.c
The text form of a bt addr is 18 bytes including nul, not 16.
=> Fix bt addr buffer overflow

src/a2dp-aac.c, src/a2dp-aptx-hd.c, src/a2dp-aptx.c, src/a2dp-codecs.h, src/a2dp-faststream.c, src/a2dp-ldac.c, src/a2dp-mpeg.c, src/a2dp-sbc.c, src/ba-transport.c, src/ba-transport.h, src/ofono.c, utils/a2dpconf.c
Also this commit fixes build break caused by missing libbsd header
file - left over from 076c837.
Fixes #475
=> Store A2DP configuration as a union of all codecs

doc/bluealsa.8.rst, src/a2dp-aac.c, src/a2dp.c, src/a2dp.h, src/bluealsa.c, src/bluealsa.h, src/main.c, test/bluealsa-mock.c
According to the A2DP spec, AAC bitrate field in the A2DP configuration
shall control CBR bit rate and the max peak bit rate for VBR mode. This
commit fixes previous incorrect behavior and removes the --aac-vbr-mode
command line option in favor of --aac-bitrate and --aac-vbr options.
Fixes #474
=> Fix A2DP specification conformance for AAC codec

NEWS, doc/bluealsa-plugins.7.rst, src/asound/20-bluealsa.conf, src/asound/bluealsa-ctl.c
It turns out that changing the A2DP codec results in DBus
InterfaceRemoved and InterfaceAdded signals, and this breaks the
CTL plugin single device mode. So we now ignore both those signals
in single device mode and instead rely on the Bluez Device
"Connected" property change to indicate that a single device has
disconnected.
Additionally, other updates that would trigger removal/addition of
control elements in single device mode are also ignored - i.e.
changing of device Alias and addition of the Battery property
after initial creation of control elements.
=> fix ctl plugin single device mode

src/asound/20-bluealsa.conf
We are updating the bluez-alsa we ship with OSMC and would like to use your 20-bluealsa.conf without patching.  Confused by the description, though. What is the thinking behind "hub"?
=> Make default description more general

src/codec-msbc.c, src/codec-msbc.h
The spandsp at https://www.soft-switch.org/ is old and not updated. A fork exist at https://github.com/freeswitch/spandsp and it turns out the old maintainer (Steve Underwood, https://github.com/coppice-git/) contributed to it until 2018:
https://github.com/freeswitch/spandsp/commits?author=coppice-git https://github.com/freeswitch/spandsp/commit/31504fd0c1ab968673234db4cc.patch
Trying to use this version currently fails, because plc_state_t is now a private structure which must be dynamically allocated:
In file included from codec-msbc.c:12:
codec-msbc.h:68:21: error: field 'plc' has incomplete type
68 |         plc_state_t plc;
|                     ^~~
Switching to plc_alloc()/plc_free() fixes the problem without breaking compatibility with the old version at www.soft-switch.org
=> Add support for more recent spandsp versions

utils/aplay/aplay.c
fixes segv in alsa-lib when the requested mixer element name does not exist.
=> initialize mixer components in bluealsa-aplay

src/ba-transport.c, test/test-ba.c
When using BlueALSA <-> BlueALSA, both HFP and HSP transports can be created at the same time. However only the last transport connected is added to the device->transports hash table. This can cause problems for the HF/HS device because when the incoming audio connection is accepted it is mapped to that second transport (eg HSP) even when ii is actually from the first (eg HFP) transport.
=> Accept only one SCO profile connection per device

doc/bluealsa-api.txt, doc/bluealsa-cli.1.rst, misc/bash-completion/bluealsa, src/ba-transport.c, src/ba-transport.h, src/bluealsa-dbus.c, src/bluealsa-dbus.h, src/bluealsa-iface.c, src/shared/dbus-client.c, src/shared/dbus-client.h, test/test-alsa-pcm.c, utils/cli/cli.c, utils/cli/cmd-monitor.c
This is a tentative proposal to implement the suggestion here:
https://github.com/Arkq/bluez-alsa/issues/536#issuecomment-1280767923
I've called the new PCM1 property "Running", but of course that can easily be changed.
I should say here that I only have a little previous experience coding the D-Bus and GLib APIs, so there may well be better ways of implementing this. However, I have found the new bluealsa-cli monitor functionality to be very useful in testing; I got good results using it in a script to launch `alsaloop` on a HF node as soon as the audio connection is established.
=> PCM "Running" property

src/io.c, test/test-alsa-pcm.c
Here's my rather simple solution to the slow client / full pipe problem mentioned in https://github.com/arkq/bluez-alsa/pull/601#issuecomment-1436569189
=> Do not allow a slow client to block the decoder thread

.github/spellcheck-wordlist.txt, doc/bluealsa.8.rst, src/a2dp.c, src/ba-transport.c, src/bluealsa-config.c, src/bluealsa-config.h, src/bluez.c, src/bluez.h, src/hci.c, src/hci.h, src/main.c, src/ofono.c, src/sco.c, src/shared/a2dp-codecs.h, src/shared/bluetooth.h, src/shared/log.h, test/Makefile.am
Enables use of mSBC with Realtek USB adapters by applying a manufacturer-specific sco socket mtu value. This PR is a temporary measure until a more general mSBC over USB fix can be found (for example PR #550). See #637 for description of the problem being addressed.
Current BlueALSA sources result in silence being played, and bluealsa debug output shows `D: ../../src/hci.c:150: USB adjusted SCO MTU: 28: 24`. With this PR, audio is played correctly and bluealsa debug output shows `D: ../../src/hci.c:150: USB adjusted SCO MTU: 28: 72`
Fixes #637
=> Fix msbc on Realtek USB adapters 

NEWS, src/ofono.c
ofono support for the HF role was broken by commit d21ed50. This PR restores that support. Fixes #640
=> Fix ofono socket authorization in HF role

INSTALL.md, configure.ac
function sbc_reinit_a2dp was not exposed in the shared library until v1.5
See #639 
Use of sbc_reinit_a2dp was added in commit 44a5dd9a17eaf3b2a92ea2d1859b64f9837f2b4a
=> SBC: Require sbc >= 1.5.

configure.ac
From https://bugs.debian.org/1006631:
> dbus supports policy files in both `/usr/share/dbus-1/system.d` and
> `/etc/dbus-1/systemd`. [The] recently released dbus 1.14.0, officially
> deprecates installing packages' default policies into `/etc/dbus-1/systemd`,
> instead reserving it for the sysadmin. This is the same idea as the
> difference between `/usr/lib/udev/rules.d` and `/etc/udev/rules.d`.
=> src/Makefile.am: Install D-Bus policy in /usr/share, not /etc

NEWS, doc/bluealsa-api.txt, doc/bluealsa-cli.1.rst, doc/bluealsa-plugins.7.rst, misc/bash-completion/bluealsa, src/asound/bluealsa-ctl.c, src/ba-transport.c, src/ba-transport.h, src/bluealsa-dbus.c, src/bluealsa-dbus.h, src/bluealsa-iface.xml, src/shared/dbus-client.c, src/shared/dbus-client.h, src/shared/defs.h, src/storage.c, test/Makefile.am, test/test-alsa-ctl.c, test/test-ba.c, test/test-utils-cli.c, utils/cli/Makefile.am, utils/cli/cli.c, utils/cli/cmd-delay-adjustment.c
See discussion #650 for rationale. Extends the D-Bus API org.bluealsa.PCM1 to allow setting a persistent adjustment that is applied to the Delay property of the PCM. Each codec supported by the PCM has its own delay adjustment.
The choice of control name for the CTL plugin is not yet agreed, and in this initial draft the name "Sync" is used.
=> Delay adjustment

NEWS, doc/bluealsa-aplay.1.rst, misc/bash-completion/bluealsa, test/test-utils-aplay.c, utils/aplay/Makefile.am, utils/aplay/aplay.c
A proposal to improve `bluealsa-aplay` volume control. Inspired by the discussion in PR #662, this proposal gives the `bluealsa-aplay` utility the ability to select soft volume or pass-through volume control independently of the `bluealsa` service defaults.
Default behavior remains unchanged, so backwards compatibility for existing installations is maintained.
See the changes to `doc/bluealsa-aplay.1.rst` for details of the new command-line option and the various new behaviors made available.
=> bluealsa-aplay: option to select volume mode

doc/bluealsa-plugins.7.rst, src/asound/bluealsa-pcm.c, test/test-alsa-pcm.c
Implement support for applications that use snd_pcm_abort() or snd_pcm_nonblock(pcm, 2) to request that blocking calls are aborted by a signal. Also apply a timeout to the local drain so that an application can not be blocked indefinitely should the bluealsa server stop reading from the PCM FIFO.
This PR is an attempt to address the plugin issues revealed indirectly by #666
=> Improve PCM plugin drain

.github/spellcheck-wordlist.txt, src/asound/bluealsa-pcm.c, src/shared/dbus-client.c, src/shared/dbus-client.h, test/test-dbus.c
Some more tweaks to the PCM plugin to help isolate it from failures in the server.
Also includes a fix for a D-Bus test failure (but it seems there is still at least one other bug in there that causes occasional failures in github actions).
=> Alsa plugin resilience

.github/workflows/build-and-test.yaml, .github/workflows/code-scanning.yaml, .github/workflows/codecov-report.yaml, NEWS, configure.ac, src/a2dp-aptx.c, src/codec-aptx.c
Some distributions now package libfreeaptx for apt-X support (because pipewire uses it rather than libopenaptx). It appears that Fedora has **only** libfreeaptx, whereas Debian includes both libopenaptx and libfreeaptx.
See #678 for more information.
=> Add support for libfreeaptx

TROUBLESHOOTING.md
Documentation update
Make it clear that BlueALSA does not permit multiple simultaneous connections to the same PCM.
=> Mention EBUSY error in troubleshooting guide

src/asound/bluealsa-pcm.c
This enables use of capture streams with applications such as MPD that require poll() to block until at least avail_min() frames have been placed into the buffer by the device (which is normal behaviour for `hw` devices).
=> ALSA PCM plugin: capture stream: do not set POLLIN flag on prepare

README.md
I've just noticed  that the line break characters in the README mermaid diagram are no longer rendering correctly. I'm not sure how long ago that happened, nor if its just my local browser setup or some update to the github mermaid parser that has changed. The first commit here fixes them for me.
There is also a second commit to add a legend panel making clear the meaning of the colours. I cannot decide whether that actually improves the readability or not, so I put it in as a separate commit.
=> Minor improvements to context diagram

src/ba-rfcomm.c, src/ba-transport.c, test/test-rfcomm.c
If a dbus client thread locks the codec_id_mtx mutex while Bluez is processing a SetConfiguration request, then that can lead to the main thread being blocked if a client calls any method that needs to read the current codec. However, the SetConfiguration request needs the main thread to be active to respond to the ClearConfiguration call that Bluez makes during its own handling of SetConfiguration. So there is a risk of deadlock if the client attempts to read the codec id while SetConfiguration is in progress. This deadlock is temporary because the dbus calls have a timeout - but Bluez handles the timeout by closing the A2DP profile connection.
There does not appear to be any clear reason why SetConfiguration needs to lock the client_id_mtx mutex, since it does not actually modify the …
=> Fix potential temporary deadlock in A2DP codec selection procedure.

src/ba-transport-pcm.c, src/ba-transport-pcm.h, src/ba-transport.h, src/bluealsa-dbus.c, src/bluez.c, test/test-rfcomm.c, test/test-utils-ctl.c, utils/aplay/Makefile.am, utils/aplay/aplay.c
This feature requires BlueZ >= 5.79
=> PCM client delay reporting for A2DP sink profile

.github/spellcheck-wordlist.txt, doc/bluealsa-aplay.1.rst, utils/aplay/alsa-pcm.c, utils/aplay/aplay.c
This PR attempts to resolve two issues I've found with the new sink delay
reporting.
The first is that although A/V sync is mostly good with BlueALSA devices as source,
my iphone is unable to sync. I found that a typical commercial sink has a delay 
between 100ms and 200ms with both SBC and AAC codecs, whereas my BlueALSA sink
has a delay of over 400ms. By adjusting the bluealsa-aplay ALSA parameters to
reduce the delay, I can achieve very good A/V sync with both the iphone and
BlueALSA sources.
The second is that although A/V sync is generally very good, it can on occasion 
be understated by over 100ms (as measured by setting the ClientDelay property on
a BlueALSA source to correct the sync). I believe this is caused by the 
relative payload sizes of the L2CAP frames, codec frames, and …
=> bluealsa-aplay delay reporting improvements

doc/a2dpconf.1.rst, src/a2dp-aac.c, src/a2dp-aptx-hd.c, src/a2dp-aptx.c, src/a2dp-faststream.c, src/a2dp-lc3plus.c, src/a2dp-ldac.c, src/a2dp-lhdc.c, src/a2dp-mpeg.c, src/a2dp-opus.c, src/a2dp-sbc.c, src/ba-transport-pcm.c, src/ba-transport-pcm.h, src/io.c, src/io.h, src/sco-cvsd.c, src/sco-lc3-swb.c, src/sco-msbc.c, src/shared/a2dp-codecs.c, src/shared/rt.c, src/shared/rt.h, test/test-a2dp.c
I've raised this as a draft PR for discussion because:
1. I'm not sure if there is a reason why D-Bus signalling was omitted originally.
2. I'm not sure of the GIO dbus thread handling. This solution emits dbus signals from the transport I/O thread, but without any locking. Is that safe?
3. My choice of a 10ms difference threshold to limit the rate that signals can be emitted is entirely arbitrary with no specific evidence to justify it.
=> Enable dbus delay signals for internal processing delay.

README.md
Help users to understand how development is organized.
=> Document the release policy

test/test-utils-aplay.c, utils/aplay/aplay.c
fixes a bug whereby a disconnecting device would cause pointers held by io_workers of other devices to become invalid.
To reproduce the error on current sources:
1.start bluealsa-aplay
2. connect device A
3. connect device B
4. start playback on device B
5. disconnect device A
6. re-connect device A
At this point the io_worker thread for device B is broken. Most often it remains blocked in poll(), sometimes it stops with error "Bad file descriptor", and on rare occasions the whole process is terminated by an abort() in libsasound.
=> aplay: allocate io_workers dynamically

.github/actions/apt-install-deps/action.yaml, .github/spellcheck-wordlist.txt, .github/workflows/build-and-test.yaml, .github/workflows/code-scanning.yaml, .github/workflows/codecov-report.yaml, NEWS, configure.ac, doc/bluealsa-aplay.1.rst, misc/bash-completion/bluealsad, src/shared/rt.h, test/test-utils-aplay.c, utils/aplay/Makefile.am, utils/aplay/alsa-pcm.c, utils/aplay/alsa-pcm.h, utils/aplay/aplay.c, utils/aplay/delay-report.c, utils/aplay/delay-report.h, utils/aplay/resampler.c, utils/aplay/resampler.h
This is my attempt to address the topics previously discussed in PR #459
The libsamplerate resampler causes high CPU usage. Its not so bad on x86_64, but really very high on armhf. I have not tried with arm64. Having said that, I have tested on an old pi zero W (32bit armv6) with the "SINC_FASTEST" converter and got very stable audio with accurate delay reporting watching a 4 hour video stream. `top` showed bluealsa-aplay consuming 28% of the (single core) CPU but the pi continued to run smoothly. So anyway this is left as an option and not included in the build by default.
=> Aplay resampler

doc/bluealsa-aplay.1.rst, src/asound/bluealsa-pcm.c, test/test-utils-aplay.c, utils/aplay/alsa-mixer.c, utils/aplay/alsa-mixer.h, utils/aplay/aplay.c
Changes aimed at clarifying some points made in issue #757
I am not convinced that "guessing" the appropriate mixer or control element would really improve the general user experience. Instead these changes try to explain more clearly what happens when explicit options for mixer device or control name are not given on the command line.
Devices that do not give dB scale TLV data are supported by assuming a simple linear scale; this is the same approach as is used by alsamixer, so should give a familiar experience for users of such devices.
=> Aplay changes

.github/workflows/build-and-test.yaml, src/asound/bluealsa-pcm.c
As discussed in https://github.com/arkq/bluez-alsa/pull/745, using the ALSA PCM transfer() callback instead of allowing the ioplug to create and manage the ring buffer fixes the TSAN test failure.
=> ALSA PCM plugin: use transfer() callback

utils/aplay/alsa-pcm.h, utils/aplay/aplay.c
Handle the situation where a BT device is in the "Running" state but delivers no audio.
Make sure that the worker thread blocks in poll() when there is no work to do.
=> aplay: prevent  busy loop
